---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/account/profile":
    get:
      summary: Profile
      tags:
      - User profile
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              example:
                data:
                  id: 1
                  type: profile
                  attribute:
                    first_name: John
                    last_name: Doe
                    full_name: John Doe
                    email: john.doe@email.com
        '401':
          description: unauthorized
  "/api/v1/registration":
    post:
      summary: Sign Up
      tags:
      - Registration
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              example:
                data:
                  id: 1
                  type: registration
                  attributes:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzZXJfaWQiOjF9fQ.2MsjQvcIt3wDxROaQN21aMFNgtdYZCYCpJrlNwmYkcc
                    user:
                      data:
                        id: 1
                        type: user
                        attribute:
                          first_name: John
                          last_name: Doe
                          full_name: John Doe
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              example:
                data:
                  id: 1
                  type: errors
                  attributes:
                    errors:
                      first_name:
                      - can't be blank
                      last_name:
                      - can't be blank
                      email:
                      - can't be blank
                      password:
                      - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                registration:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
  "/api/v1/sessions":
    post:
      summary: Sign In
      tags:
      - Session
      parameters: []
      responses:
        '201':
          description: session created
          content:
            application/json:
              example:
                data:
                  id: 1
                  type: session
                  attributes:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzZXJfaWQiOjF9fQ.2MsjQvcIt3wDxROaQN21aMFNgtdYZCYCpJrlNwmYkcc
                    user:
                      data:
                        id: 1
                        type: user
                        attribute:
                          first_name: John
                          last_name: Doe
                          full_name: John Doe
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                session:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - session
servers:
- url: https://localhost:5000
  variables:
    defaultHost:
      default: localhost
