default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 5 } %> 
  password: <%= ENV.fetch("DB_PASSWORD") { 5 } %> 

development:
  <<: *default
  database: app_api_development

test:
  <<: *default
  database: app_api_test

production:
  <<: *default
  database: app_api_production
  username: app_api
  password: <%= ENV['APP_API_DATABASE_PASSWORD'] %>
